version: "3"

services:
  db:
    container_name: postgres
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
  api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
volumes:
  postgres-db-data:
    driver: local
  pgadmin-data:
